apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-unused 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman-unused
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pacman-unused
    spec:
      containers:
        - image: quay.io/jduimovich0/pacman-unused
          imagePullPolicy: Always
          name: container-image
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
        - image: quay.io/redhat-user-workloads-stage/ysubrama-tenant/mongo-pacman/mongodb@sha256:656b38905313877ff8d1df694a0f4a6a66f77fd94a3ec128fc608dc3ddba5129
          imagePullPolicy: Always
          name: mongo-image
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 10m
              memory: 512Mi              