apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mongodb
    spec:
      containers:
        - image: quay.io/jduimovich0/mongoserver:2023-03-09-082829
          imagePullPolicy: Always
          name: container-image
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
---
apiVersion: v1
data:
  POSTGRESQL_DATABASE: rhtrex
  POSTGRESQL_PASSWORD: foobar-bizz-buzz
  POSTGRESQL_USER: trex
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pg-rh-trex--env
  name: pg-rh-trex--env            
